name: CocoroTricks CI

on:
  # 手动触发（可选同时推广到生产）
  workflow_dispatch:
    inputs:
      promote_to_production:
        description: "Type yes to promote to production"
        required: true
        default: "no"
  # PR 打开/更新时自动触发
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Install deps
        run: |
          npm ci || npm i
          npx playwright install --with-deps
      - name: Playwright tests
        run: npx playwright test

  guard:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run guard thresholds
        run: node scripts/guard-clb.js

  # —— 仅 PR 场景：等待你在 PR 评论里输入 /approve-staging —— #
  approval-staging:
    if: github.event_name == 'pull_request'
    needs: [ guard ]
    runs-on: ubuntu-latest
    steps:
      - name: Await manual approval via PR comment
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: ${{ github.repository_owner }}
          minimum-approvals: 1
          issue-number: ${{ github.event.pull_request.number }}
          approval-type: comment
          approve-word: "/approve-staging"
          reject-word: "/reject"

  # —— PR 场景：审批通过才部署到 staging —— #
  deploy-staging:
    if: github.event_name == 'pull_request'
    needs: [ approval-staging ]
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to staging (placeholder)
        run: echo "Deploying to staging from PR (approved) ..."

  # —— 手动触发场景：无需评论审批，直接部署到 staging —— #
  deploy-staging-manual:
    if: github.event_name == 'workflow_dispatch'
    needs: [ guard ]
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to staging (manual dispatch)
        run: echo "Deploying to staging from manual run ..."

  # —— 手动触发时，如输入 yes，再推广到生产 —— #
  promote-production:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.promote_to_production == 'yes'
    needs: [ deploy-staging-manual ]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: "Promote to production (manual confirm: yes)"
        run: echo "Promote to production"

  # 失败回滚占位（任意失败都会触发）
  rollback:
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Rollback (placeholder)
        run: echo "Rollback triggered"
