name: CocoroTricks CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      promote_to_production:
        description: "Type yes to promote to production"
        required: true
        default: "no"

jobs:
  # 测试 Job（简化，占位）
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dummy test
        run: echo "Run tests (placeholder)"

  # 守门 Job（占位，后续可加逻辑）
  guard:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - name: Guard check
        run: echo "Guard thresholds checked"

  # 审批 Job —— 等待你在 PR 评论输入 /approve-staging
  approval-staging:
    needs: [ guard ]
    runs-on: ubuntu-latest
    steps:
      - name: Await manual approval via PR comment
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: ${{ github.repository_owner }}
          minimum-approvals: 1
          issue-number: ${{ github.event.pull_request.number }}
          approval-type: comment
          approve-word: "/approve-staging"
          reject-word: "/reject"

  # 部署到 staging（审批通过后才会跑）
  deploy-staging:
    needs: [ approval-staging ]
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to staging (placeholder)
        run: echo "Deploying to staging..."

  # 手动触发生产部署（workflow_dispatch 输入 yes 才执行）
  promote-production:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.promote_to_production == 'yes'
    needs: [ deploy-staging ]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Promote to production (manual confirm: yes)
        run: echo "Promote to production"

  # 失败回滚（任意失败都会触发）
  rollback:
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Rollback (placeholder)
        run: echo "Rollback triggered"
