name: CocoroTricks CI

on:
  pull_request:
    branches: [ main ]      # PR 阶段只跑到 staging
  push:
    branches: [ main ]      # 合并到 main 后再尝试发布到 production（会卡在环境审批）

permissions:
  contents: read

concurrency:
  group: cocorotricks-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # 测试 Job（占位）
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dummy test
        run: echo "Run tests (placeholder)"

  # 守门 Job（占位）
  guard:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Guard thresholds checked
        run: echo "Guard thresholds checked"

  # 部署到 staging（PR 上触发；需 staging 环境已设置 Required reviewers）
  deploy-staging:
    if: github.event_name == 'pull_request'
    needs: [guard]
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to staging
        run: echo "Deploying to staging..."

  # 部署到 production（仅在 push 到 main 时触发；由生产环境审批放行）
  deploy-production:
    if: github.event_name == 'push'
    needs: [guard]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to production
        run: echo "Deploying to production..."

  # 失败回滚（占位）
  rollback:
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Rollback (placeholder)
        run: echo "Rollback triggered"
