name: Demo CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  staging:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - run: echo "Hello Staging"

  production:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo "Hello Production"
# test commit
